### ISSUE TITLE
Not working in Mint 19

### ISSUE THREAD

**Issue by luhis** [sridwan/Ubuntu-Kernel-for-Teclast-F7#1]
Hi there,

In theory this should work in Mint 19, but I am finding that the touchpad does not work at all with this kernel installed.

What can i do to try and fix it?

**Comment by sridwan** [comment]
Maybe you can try compiling Mint's kernel.
I use this guide to compile mine [http://strangequark.tk/index.php/blog/20180423_teclastf7linux](http://strangequark.tk/index.php/blog/20180423_teclastf7linux)

**Comment by sridwan** [comment]
Did you manage to have your touchpad working?
